preset: laravel
risky: true
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - docs
  name: "*.php"
  not-name: "*.blade.php"
enabled:
  - concat_with_spaces
disabled:
  - function_declaration
