preset: laravel
risky: true
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - docs
  name: "*.php"
  not-name: "*.blade.php"
disabled:
  - concat_without_spaces
  - function_declaration
  - not_operator_with_successor_space
